### ISSUE TITLE
Doesn't properly render CJK Unicode range

### ISSUE THREAD

**Issue by nivekmai** [premieroctet/screen-guru#2]
https://2s9e3bif52.execute-api.eu-central-1.amazonaws.com/production/screenshot?url=Google.cn&color=E9D460

**Comment by baptadn** [comment]
Thanks for the report! It's now fixed (a244f73cb1ede24fc4bf1eb7cc0cdd8d34ed47de), I've added the [Noto Sans CJK font](https://www.google.com/get/noto/#sans-hant):

![image](https://user-images.githubusercontent.com/1102595/50142787-3e560a00-02ab-11e9-8a63-cc38e2b68801.png)
