### ISSUE TITLE
Add timeout for text animation to occur (or use a js idle detection ?)

### ISSUE THREAD

**Issue by tlenclos** [premieroctet/screen-guru#5]
See https://2s9e3bif52.execute-api.eu-central-1.amazonaws.com/production/screenshot?url=https://mfglabs.com/&color=E9D460

![image](https://user-images.githubusercontent.com/686101/50217208-5d769980-0388-11e9-8d46-f9ddc321dcb7.png)

![image](https://user-images.githubusercontent.com/686101/50217219-64051100-0388-11e9-9be3-d98cc6b7cf2d.png)

**Comment by baptadn** [comment]
Fixed with c15ce2c5b0a074585b1b05529a19f5b7c2645c2b (increase animation speed and add some delay)

![image](https://user-images.githubusercontent.com/1102595/50483269-4f112900-09eb-11e9-8ba1-fa49386e67b4.png)
