### ISSUE TITLE
Handle proxy filter

### ISSUE THREAD

**Issue by tlenclos** [premieroctet/screen-guru#6]
see https://2s9e3bif52.execute-api.eu-central-1.amazonaws.com/production/screenshot?url=https://www.bam.tech/&color=E9D460

Seems to be cloudflare on this one.

![image](https://user-images.githubusercontent.com/686101/50217245-797a3b00-0388-11e9-81ea-2f840584aff0.png)

**Comment by baptadn** [comment]
I removed the google bot user agent, it's fixed (I think Cloudflare checks the integrity of IP / user agent)

![image](https://user-images.githubusercontent.com/1102595/50483304-93042e00-09eb-11e9-8ec2-5fc7148c99cd.png)
