### ISSUE TITLE
[New feature] Take into account an anchor in a link

### ISSUE THREAD

**Issue by jacquelotjeff** [premieroctet/screen-guru#7]
Very useful project, good job :) 

I think it can be nice to take into account an anchor in a link (if we want to include only a special part of the website for example).

**Comment by baptadn** [comment]
Thanks! It's fixed with c080dd5b998e4886521473c86dbd53a2e07d712b

Ex: https://reactjs.org/docs/hooks-reference.html#uselayouteffect

![image](https://user-images.githubusercontent.com/1102595/50739582-eb54e000-11e2-11e9-9fe2-5dab56613cb0.png)
