### ISSUE TITLE
screenguru is ko error on build

### ISSUE THREAD

**Issue by chrismccoy** [premieroctet/screen-guru#9]
ive done yarn install and build for static deployment, but everytime i enter a url i get the error 

    The Guru is KO. You can submit an issue or try later. Sorry

any ideas @shinework

**Comment by baptadn** [comment]
Hi @chrismccoy 👋, have you deploy the lamdba and set the env var `REACT_APP_LAMBDA_ENDPOINT` in .env with your lambda endpoint ?

**Comment by chrismccoy** [comment]
no, i am just deploying without aws lamdba to my own server just using yarn build, and pointing docroot at the build directory @shinework

**Comment by baptadn** [comment]
The node screen service can't be run on a static server, you have to deploy the [screenshot service](https://github.com/premieroctet/screen-guru/tree/master/lambda/screenshot) on AWS Lambda

**Comment by chrismccoy** [comment]
ahh ok, thought it could be run on its own server away from aws
